### ISSUE TITLE
界面主題配色 / Support more themes

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#107]
目前"檢視區塊"是白色的，建議可以有暗色系的版本可切換，
同樣的"編輯區塊"也建議有亮色系可切換。
如果可以的話，能自己選色配置也是不錯。

> Now only have white theme in "view" area, it would be nice to have some dark theme available.
> Also suggest the "edit" area have some light theme to choose.
> It would be better than enough if user can setup their own themes.

**Comment by jackycute** [comment]
Support light editor theme in 09fb1209678b2acc18ee13ee0c407278e67d2c06

**Comment by jimmybrancaccio** [comment]
@jackycute You mean dark theme?

**Comment by jackycute** [comment]
@jimmybrancaccio No, I mean light theme of editor.
The toggle showing on below image.

<img width="614" alt="2016-06-19 4 59 30" src="https://cloud.githubusercontent.com/assets/2639151/16241770/c4f7bd8a-3821-11e6-8068-247e4160bae7.png">

**Comment by jimmybrancaccio** [comment]
@jackycute Ah okay, I was reading the issue/comment and code wrong then :P Carry on!

**Comment by almereyda** [comment]
As per the Original Posting (OP) I suggest to rename this issue more specifically to *Support night theme*, which appears to be the main concern here.

**Comment by sedrubal** [comment]
Here are some suggestions, but that covers only the easy things :smile: tables, code and some other things are still missing:

```css
/* hackmd dark theme */
html, body, .markdown-body img {
  background-color: #242934;
  color: #D3DAE3;
}
.markdown-body h1, .markdown-body h2, .markdown-body h3, .markdown-body h4, .markdown-body h5, .markdown-body h6, .markdown-body hr {
  border-color: #444;
}
.ui-toc-dropdown .nav > .active:focus > a, .ui-toc-dropdown .nav > .active:hover > a, .ui-toc-dropdown .nav > .active > a {
  color: #D3DAE3;
  border-left-color: #337AB7;
}
.ui-toc-dropdown .nav > li > a:focus, .ui-toc-dropdown .nav > li > a:hover {
  color: #AAA;
  border-left-color: #337AB7;
}
.markdown-body blockquote {
  color: #AAA;
  border-left-color: #444;
}
```
