### ISSUE TITLE
LDAP auth broken in 0.5.1

### ISSUE THREAD

**Issue by esbite** [hackmdio/hackmd#413]
We have been using a docker image built on master 6587e7c. In that version the LDAP auth works great and we use it daily. But we would like to switch to version 0.5.1 instead to base our docker image off a stable version tag, instead of just a commit on master, but in this version the LDAP auth doesn't work :sad:

We are using the latest `hackmdio/hackmd:lite`. That is probably built with 0.5.1? (See separate issue about tagging your lite versions https://github.com/hackmdio/docker-hackmd/issues/11)

Here is the error hackmd logs when we try to authenticate with LDAP. Nothing has changed other than the base image, we are setting our environment variables just like before: `HMD_LDAP_URL=ldaps://ldap.internal:636`
```
hackmd_1    | AssertionError: LDAP server URL not defined (opts.url)
hackmd_1    |     at new LdapAuth (/hackmd/node_modules/ldapauth-fork/lib/ldapauth.js:102:10)
hackmd_1    |     at Strategy.handleAuthentication (/hackmd/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js:166:10)
hackmd_1    |     at Strategy.authenticate (/hackmd/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js:210:33)
hackmd_1    |     at attempt (/hackmd/node_modules/passport/lib/middleware/authenticate.js:348:16)
hackmd_1    |     at authenticate (/hackmd/node_modules/passport/lib/middleware/authenticate.js:349:7)
hackmd_1    |     at /hackmd/app.js:393:11
hackmd_1    |     at Layer.handle [as handle_request] (/hackmd/node_modules/express/lib/router/layer.js:95:5)
hackmd_1    |     at next (/hackmd/node_modules/express/lib/router/route.js:131:13)
hackmd_1    |     at /hackmd/node_modules/body-parser/lib/read.js:129:5
hackmd_1    |     at invokeCallback (/hackmd/node_modules/raw-body/index.js:262:16)
hackmd_1    |     at done (/hackmd/node_modules/raw-body/index.js:251:7)
hackmd_1    |     at IncomingMessage.onEnd (/hackmd/node_modules/raw-body/index.js:307:7)
hackmd_1    |     at emitNone (events.js:86:13)
hackmd_1    |     at IncomingMessage.emit (events.js:185:7)
hackmd_1    |     at endReadableNT (_stream_readable.js:974:12)
hackmd_1    |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by jackycute** [comment]
I don't see any commits could stop LDAP working.
Maybe is the tagging and docker:lite have some problems.
We'll look into it, thanks @esbite

**Comment by a60814billy** [comment]
Hi , 

1. The error message seems incorrect `HMD_LDAP_URL` setting .
I tested both of `hackmdio/hackmd:lite` and `hackmdio/hackmd:0.5.1` image, the LDAP auth are work. But I only tested LDAP protocol.

2. `hackmdio/hackm:lite` is the newest release version of HackMD. It's build 0.5.1 now.

Below is my `docker-compose.yml` file, 

```yaml
version: '3'
services:
  ldap:
    build: ./ldap
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
  hackmd:
    image: hackmdio/hackmd:0.5.1
    environment:
      - HMD_LDAP_URL=ldap://ldap
      - HMD_LDAP_SEARCHBASE=ou=people,dc=example,dc=com
      - HMD_LDAP_SEARCHFILTER=(uid={{username}})
      - HMD_DB_URL=postgres://hackmd:hackmdpass@postgres:5432/hackmd
    links:
      - ldap:ldap
      - postgres:hackmdPostgres
    ports:
      - "3000:3000"
```
