### ISSUE TITLE
Remove URLs next to links when export to PDF using browser built-in print

### ISSUE THREAD

**Issue by AntonioTsai** [hackmdio/hackmd#535]
When I export a note to PDF by Chrome built-in print, the URL will show next to the link,
like this
![screen shot 2017-08-27 at 23 13 49](https://user-images.githubusercontent.com/10348054/29751254-75f15b00-8b7d-11e7-8673-c3f1fa5a628e.png)

The link is still available after export to PDF, so it seems we can remove the URL after the link?
And this can be done by adding CSS rule.
```css
@media print {
    a[href]::after {
        content: none !important;
    }
}
```
